"""Deterministic strategy methodology cards.

These cards translate research reports into executable planning context. They
are analysis-only: useful for overnight planning and implementation sequencing,
but they do not create trade intents or broker orders.
"""

from __future__ import annotations

from typing import Any

from tradingagents.dataflows._official_common import evidence_packet, request_hash

FORBIDDEN_EFFECTS = [
    "create_trade_intent",
    "size_position",
    "submit_order",
    "promote_sleeve",
    "waive_live_gate",
]


STRATEGY_METHOD_CARDS: list[dict[str, Any]] = [
    {
        "sleeve": "breakout-continuation",
        "phase": "active_supervisor_style",
        "role": "cleaned_up_current_aggressive_momentum",
        "hypothesis": "Strong liquid leaders can continue when price, volume, catalyst, and market context confirm without being too extended.",
        "inputs": [
            "relative_strength_vs_spy_qqq_and_sector",
            "short_term_momentum",
            "volume_expansion_quality",
            "gap_or_breakout_retention",
            "fresh_catalyst_or_market_tailwind",
            "liquidity_and_spread",
            "distance_from_support_and_atr_extension",
        ],
        "entry_checks": [
            "price strength is confirmed by sector or index context",
            "volume supports accumulation rather than exhaustion",
            "breakout or gap level is retained after first reaction",
            "setup is not already too extended versus ATR and support",
        ],
        "vetoes": [
            "exhaustion_gap",
            "late_chase_far_above_support",
            "sector_divergence",
            "low_quality_or_stale_catalyst",
            "wide_spread",
            "stale_core_market_data",
        ],
        "exit_rules": [
            "breakout_level_lost",
            "relative_strength_reversal",
            "volume_exhaustion",
            "target_or_time_stop",
        ],
        "can_affect_execution": "current_supervisor_and_paper_tournament_only_after_existing_gates",
    },
    {
        "sleeve": "pullback-support",
        "phase": "active_paper_first",
        "role": "default_buy_the_dip_engine",
        "hypothesis": "Controlled retracements inside intact leadership can rebound when the move is non-fundamental.",
        "inputs": [
            "rising_50d_and_200d_trend",
            "support_zone_distance",
            "atr_pullback_depth",
            "sell_volume_deceleration",
            "sector_relative_strength",
            "fresh_negative_event_absent",
            "earnings_and_macro_blackout_state",
            "liquidity_and_spread",
        ],
        "entry_checks": [
            "price remains above rising intermediate trend anchors",
            "pullback depth is controlled, usually 0.75 to 2.5 ATR",
            "support level is precomputed and not invented after the move",
            "sell volume is slowing or gap is reclaimed",
            "sector or peer context is not breaking down",
        ],
        "vetoes": [
            "falling_200d",
            "broken_breakout_without_reclaim",
            "no_clean_support",
            "greater_than_3_atr_without_reclaim",
            "expanding_down_volume",
            "large_unreclaimed_gap",
            "sector_breakdown",
            "earnings_blackout",
            "fresh_negative_sec_or_news_event",
            "stale_core_market_data",
        ],
        "exit_rules": [
            "support_failure_close",
            "time_stop_if_no_reversal_evidence",
            "fresh_negative_event",
            "regime_deterioration",
        ],
        "can_affect_execution": "paper_intent_only_after_deterministic_policy",
    },
    {
        "sleeve": "earnings-drift",
        "phase": "research_to_paper_queue",
        "role": "post_earnings_underreaction",
        "hypothesis": "Fundamental information can be incorporated over days after earnings, guidance, and revision shocks.",
        "inputs": [
            "earnings_calendar",
            "actual_vs_consensus",
            "guidance_or_transcript_change",
            "analyst_revision_direction",
            "post_event_gap_retention",
            "sector_confirmation",
            "slippage_and_spread",
        ],
        "entry_checks": [
            "event timestamp is known and not lookahead contaminated",
            "post-event price holds key gap or reaction level",
            "news and revisions do not contradict the direction",
            "liquidity supports limit-only entry",
        ],
        "vetoes": [
            "unresolved_event_before_entry",
            "stale_or_missing_earnings_timestamp",
            "official_contradiction",
            "wide_spread",
            "event_gap_failure",
        ],
        "exit_rules": [
            "drift_window_expired",
            "reaction_level_lost",
            "revision_reversal",
            "target_or_time_stop",
        ],
        "can_affect_execution": "research_only_until_preregistered_and_validated",
    },
    {
        "sleeve": "pairs-comovement-residual",
        "phase": "research_to_paper_queue",
        "role": "relationship_residual_trade",
        "hypothesis": "Related assets can temporarily diverge from a stable relationship and mean-revert after common-factor stripping.",
        "inputs": [
            "industry_or_etf_relationship",
            "rolling_correlation",
            "rolling_hedge_ratio",
            "cointegration_or_residual_stability",
            "spread_zscore",
            "half_life",
            "event_blackout_for_both_legs",
            "shortability_if_short_leg_needed",
        ],
        "entry_checks": [
            "relationship is interpretable before statistical testing",
            "residual is stable enough in recent windows",
            "divergence exceeds threshold and is not event-driven damage",
            "both legs pass liquidity constraints",
        ],
        "vetoes": [
            "structural_break",
            "earnings_or_material_event_near_one_leg",
            "borrow_or_short_unavailable",
            "relationship_not_interpretable",
            "spread_widening_on_new_information",
        ],
        "exit_rules": [
            "spread_mean_reversion",
            "half_life_time_stop",
            "structural_break_detected",
            "event_risk_appears",
        ],
        "can_affect_execution": "research_only_until_long_only_policy_decides_supported_variant",
    },
    {
        "sleeve": "event-catalyst-continuation",
        "phase": "research_to_paper_queue",
        "role": "scheduled_or_discrete_event_swing",
        "hypothesis": "Credible catalysts can continue when price, sector, and event context confirm instead of fading.",
        "inputs": [
            "sec_8k_or_official_event",
            "macro_release_calendar",
            "corporate_actions",
            "news_freshness",
            "gap_retention",
            "relative_volume",
            "peer_confirmation",
        ],
        "entry_checks": [
            "catalyst source is official or high-quality",
            "reaction is retained after initial volatility",
            "calendar risk is not immediately ahead",
            "sector and peers do not contradict",
        ],
        "vetoes": [
            "low_quality_source_only",
            "stale_catalyst",
            "official_contradiction",
            "major_macro_event_window",
            "spread_or_liquidity_failure",
        ],
        "exit_rules": [
            "event_midpoint_lost",
            "follow_up_contradiction",
            "time_decay",
            "target_or_stop",
        ],
        "can_affect_execution": "research_only_until_paper_policy_exists",
    },
    {
        "sleeve": "news-sentiment-swing",
        "phase": "research_to_paper_queue",
        "role": "text_and_social_context_confirmation",
        "hypothesis": "Fresh high-quality news and broad sentiment shocks can confirm continuation or warn that price action is a trap.",
        "inputs": [
            "alpaca_news_or_high_quality_news",
            "google_news_rss_cluster",
            "reddit_and_social_context_flags",
            "entity_mapping",
            "source_quality_score",
            "duplicate_news_cluster_state",
            "price_reaction_after_news",
        ],
        "entry_checks": [
            "news timestamp is fresh and source quality is high enough",
            "entity mapping clearly refers to the ticker",
            "price reaction agrees with non-stale evidence",
            "social chatter is used as context only, not trade truth",
        ],
        "vetoes": [
            "low_quality_source_only",
            "stale_news",
            "ambiguous_entity_mapping",
            "duplicate_article_echo",
            "social_hype_without_price_or_primary_source_confirmation",
        ],
        "exit_rules": [
            "news_contradiction",
            "sentiment_reversal",
            "event_window_expired",
            "price_reaction_fails",
        ],
        "can_affect_execution": "advisory_only_until_replay_ablation_proves_incremental_value",
    },
    {
        "sleeve": "mean-reversion-swing",
        "phase": "research_to_paper_queue",
        "role": "controlled_overreaction_reversal",
        "hypothesis": "Liquid stocks can mean-revert after short-horizon overreaction when trend damage, event risk, and forced selling are absent.",
        "inputs": [
            "multi_day_return_zscore",
            "atr_extension",
            "rsi_or_oscillator_extreme",
            "sector_adjusted_return",
            "volume_behavior",
            "event_blackout_state",
            "support_or_prior_range",
        ],
        "entry_checks": [
            "move is stretched versus recent volatility",
            "sector-adjusted damage is not structural",
            "volume does not show unresolved panic distribution",
            "support or prior range gives a clear invalidation level",
        ],
        "vetoes": [
            "fresh_negative_event",
            "earnings_blackout",
            "broken_intermediate_trend",
            "expanding_down_volume",
            "no_clear_invalidator",
        ],
        "exit_rules": [
            "mean_reversion_band_reached",
            "support_failure",
            "time_stop",
            "new_information_invalidates_reversal",
        ],
        "can_affect_execution": "research_only_until_pullback_policy_or_separate_paper_sleeve_exists",
    },
    {
        "sleeve": "macro-regime-overlay",
        "phase": "overlay_only",
        "role": "permission_and_size_modifier",
        "hypothesis": "Macro regime changes risk permission and sizing, but is not a standalone ticker alpha trigger.",
        "inputs": [
            "fred_alfred_vintages",
            "fed_bls_bea_release_calendars",
            "yield_curve",
            "financial_stress",
            "labor_inflation_growth_trends",
        ],
        "entry_checks": [
            "release timestamp is point-in-time safe",
            "vintage/realtime period is recorded",
            "macro state is used as overlay not direct trade trigger",
        ],
        "vetoes": [
            "high_impact_release_window",
            "stale_macro_series",
            "revision_unaware_backtest_feature",
        ],
        "exit_rules": [
            "regime_deteriorates",
            "release_surprise_invalidates_permission",
        ],
        "can_affect_execution": "downrank_veto_or_size_down_only_inside_existing_policy",
    },
    {
        "sleeve": "factor-quality-overlay",
        "phase": "overlay_only",
        "role": "portfolio_tilt_and_risk_context",
        "hypothesis": "Quality, value, profitability, low-beta, and momentum factor context can improve sizing and avoid disguised beta.",
        "inputs": [
            "fundamental_quality_metrics",
            "valuation_or_value_proxy",
            "profitability_trend",
            "low_beta_or_defensive_proxy",
            "factor_exposure_vs_spy_qqq_sector",
            "crowding_or_concentration_state",
        ],
        "entry_checks": [
            "factor data is recent enough for the intended horizon",
            "factor evidence modifies a sleeve rather than replacing sleeve evidence",
            "portfolio exposure remains within name, sector, and beta caps",
        ],
        "vetoes": [
            "stale_fundamental_data",
            "factor_only_trade_without_sleeve_trigger",
            "portfolio_concentration_breach",
            "hidden_beta_exposure",
        ],
        "exit_rules": [
            "factor_thesis_deteriorates",
            "portfolio_cap_breach",
            "underlying_sleeve_exit",
        ],
        "can_affect_execution": "size_down_or_rank_modifier_only_until_factor_ablation_passes",
    },
    {
        "sleeve": "microstructure-execution-overlay",
        "phase": "execution_overlay_only",
        "role": "better_limit_order_timing",
        "hypothesis": "Spread, quote, and liquidity state should improve limit-order patience and avoid bad fills, not create standalone alpha for this cadence.",
        "inputs": [
            "latest_quote",
            "bid_ask_spread",
            "market_clock",
            "session_state",
            "average_dollar_volume",
            "limit_price_collars",
        ],
        "entry_checks": [
            "spread is narrow enough for limit-only order",
            "market session supports the order type",
            "limit price is inside configured collars",
            "liquidity supports the requested notional",
        ],
        "vetoes": [
            "wide_spread",
            "stale_quote",
            "market_closed_without_extended_hours_permission",
            "insufficient_liquidity",
            "price_collar_breach",
        ],
        "exit_rules": [
            "cancel_stale_order",
            "refresh_limit_after_quote_change",
            "do_not_chase_fill",
        ],
        "can_affect_execution": "order_quality_gate_only_not_alpha_sleeve",
    },
]


def build_methodology_cards_packet():
    source_ref = "local://reports/deep-research-report-30-31#strategy_methodology_cards"
    return evidence_packet(
        source_name="strategy_methodology_cards",
        evidence_type="methodology_cards",
        subject="TradingAgents strategy sleeve methodology cards",
        source_ref=source_ref,
        payload={
            "cards": STRATEGY_METHOD_CARDS,
            "execution_authority": "none",
            "analysis_only": True,
            "forbidden_effects": FORBIDDEN_EFFECTS,
            "default_build_order": [
                "breakout-continuation",
                "pullback-support",
                "earnings-drift",
                "event-catalyst-continuation",
                "news-sentiment-swing",
                "pairs-comovement-residual",
                "mean-reversion-swing",
                "macro-regime-overlay",
                "factor-quality-overlay",
                "microstructure-execution-overlay",
            ],
            "coverage_status": {
                "active_order_paths": [
                    "current-aggressive",
                    "pullback-support",
                    "catalyst-relative-strength",
                ],
                "research_only_or_overlay": [
                    "breakout-continuation",
                    "earnings-drift",
                    "event-catalyst-continuation",
                    "news-sentiment-swing",
                    "pairs-comovement-residual",
                    "mean-reversion-swing",
                    "macro-regime-overlay",
                    "factor-quality-overlay",
                    "microstructure-execution-overlay",
                ],
                "intentionally_deferred": [
                    "true_etf_arbitrage",
                    "options_overlays",
                    "volatility_arbitrage",
                    "short_biased_pairs",
                    "calendar_seasonality_as_standalone_alpha",
                ],
            },
            "plain_english": (
                "Candidate ranking is only a study list. A named sleeve must pass "
                "its own deterministic feature checks before paper orders, and live "
                "still requires promotion plus the unified live gate."
            ),
        },
        quality="medium",
        request_fingerprint=request_hash(
            "LOCAL",
            source_ref,
            None,
            {"card_count": len(STRATEGY_METHOD_CARDS)},
        ),
        tool_route="local_methodology_cards",
        redaction_status="no_secrets_seen",
        freshness_extra={"read_only": True, "card_count": len(STRATEGY_METHOD_CARDS)},
    )
